management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

#On the properties 'include' is not the best practice to exposure all the endpoint,
#but we are practicing basic configuration, so we will expose every endpoint we have. Another way to do this is making a list for what we want to expose like this:
#include:
#  - info
#  - heath
#  - etc

#shutdown:
#  enabled: true
#
#This config also it's not a good practice, because this allows me to shut down a server with an API.
#This really can't happen on a productive environment.

#'info' allows me to have more information about my server